### ISSUE TITLE
East and West keywords fail with "ModuleNotFoundError: No module named 'numpy'"

### ISSUE THREAD

**Issue by vitorgalvao** [bjornelvar/alfred_nba_scores#5]
Debugger output:

```
[17:24:07.608] ERROR: NBA Scores[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4E7A25E6-195E-4C16-B296-9419E629DF97/./nba_west_standings.py", line 2, in <module>
    from lib.nba_api.stats.endpoints.leaguestandings import LeagueStandings
  File "/Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4E7A25E6-195E-4C16-B296-9419E629DF97/lib/nba_api/stats/endpoints/__init__.py", line 140, in <module>
    from .alltimeleadersgrids import AllTimeLeadersGrids
  File "/Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4E7A25E6-195E-4C16-B296-9419E629DF97/lib/nba_api/stats/endpoints/alltimeleadersgrids.py", line 1, in <module>
    from lib.nba_api.stats.endpoints._base import Endpoint
  File "/Users/vm/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.4E7A25E6-195E-4C16-B296-9419E629DF97/lib/nba_api/stats/endpoints/_base.py", line 2, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by bjornelvar** [comment]
Just pushed a fix, this was related to some get_dataframe() method within the npa_api package which is never used. Commented out for now.
